language: python
python:
        - "3.5"
        - "3.6"
before_install:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
install:
        - "pip install -r requirements.txt -r dev-requirements.txt"
before_script:
        - ./cc-test-reporter before-build        
script:
        - "pytest --cov=statement_renamer tests"
after_script:
        - ./cc-test-reporter --token $CODECLIMATE_REPO_TOKEN
        - codecov --token $CODECLIMATE_REPO_TOKEN
